//export const BASE_URL = 'https://api.bookmyheart.in';
export const BASE_URL = 'http://localhost:7777';
export const totalskills = [
    "JavaScript",
    "React",
    "Node.js",
    "CSS",
    "HTML",
    "Python",
    "Java",
    "C++",
    "MongoDB",
    "TypeScript",
    "Express.js",
    "Redux",
    "Angular",
    "Vue.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "PostgreSQL",
    "MySQL",
    "GraphQL",
    "REST API",
    "Kubernetes",
    "Docker",
    "CI/CD",
    "AWS",
    "Azure",
    "Google Cloud",
    "Linux",
    "Git",
    "GitHub",
    "Jenkins",
    "Webpack",
    "Babel",
    "SASS",
    "Bootstrap",
    "TailwindCSS",
    "jQuery",
    "Go",
    "Kotlin",
    "Swift",
    "Scala",
    "PHP",
    "WordPress",
    "Terraform",
    "Kafka",
    "Hadoop",
    "Elasticsearch",
    "Firebase",
    "Machine Learning",
    "Deep Learning",
    "Data Analysis",
    "Data Visualization",
    "Figma",
    "Adobe XD",
    "UI/UX Design",
    "Testing (Jest, Mocha)",
    "Agile Methodology",
    "Scrum"
];  